# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AgrarForum' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'ModernSearchBar'
  target 'AgrarForumTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AgrarForumUITests' do
    # Pods for testing
  end

end
